[package]
name = "msm-webgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.18.0"
pollster = "0.3.0"
bytemuck = "1.14.0"
ark-ec = "0.4.2"
ark-std = "0.4.0"
ark-curve25519 = "0.4.0"
ark-ff = "0.4.2"
num-bigint = "0.4.4"
itertools = "0.12.0"
num-traits = "0.2.17"
